services:
  exec_lab:
    build: .
    volumes:
      - ./workspace:/workspace
    stdin_open: true
    tty: true
    privileged: true
    security_opt:
      - seccomp:unconfined
    command: tail -f /dev/null
